//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertsByTicket
    {
        public long Id { get; set; }
        public long TicketId { get; set; }
        public byte AlertId { get; set; }
        public string Data { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
