//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Connection()
        {
            this.Persons = new HashSet<Person>();
        }
    
        public long Id { get; set; }
        public long PersonId { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public string SessionCode { get; set; }
        public string HostAddress { get; set; }
        public string FirmwareVersion { get; set; }
        public System.DateTime Started { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Persons { get; set; }
    }
}
