//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Persons = new HashSet<Person>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public long Id { get; set; }
        public long PersonId { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public string ConnectingSession { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime DeviceDate { get; set; }
        public System.DateTime ServerDate { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public decimal Speed { get; set; }
        public int Course { get; set; }
        public int MoveDistance { get; set; }
        public string GPSstatus { get; set; }
        public byte SatellitesNumber { get; set; }
        public byte GPSFixedStatus { get; set; }
        public int HDOP { get; set; }
        public string MCC { get; set; }
        public string LAC { get; set; }
        public string CellID { get; set; }
        public string AlarmStatus { get; set; }
        public decimal BatteryVoltage { get; set; }
        public int BatteryPercentage { get; set; }
        public byte GSMSignal { get; set; }
        public bool BeltStatus { get; set; }
        public bool ShellStatus { get; set; }
        public int ChargeStatus { get; set; }
        public bool LowPowerStatus { get; set; }
        public bool DataLoggerStatus { get; set; }
        public bool StillStatus { get; set; }
        public bool EnableAlarmsStatus { get; set; }
        public bool BuzzerStatus { get; set; }
        public bool VibratorStatus { get; set; }
        public bool RFConnectionStatus { get; set; }
        public bool RFGsensorStatus { get; set; }
        public bool RFPlugStatus { get; set; }
        public bool RestrictedAreasStatus { get; set; }
        public bool RestrictedPersonsStatus { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Persons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
