//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonsByGroup
    {
        public long Id { get; set; }
        public long PersonId { get; set; }
        public long GroupId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Person Person { get; set; }
    }
}
