//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsesByTicket
    {
        public long Id { get; set; }
        public long TicketId { get; set; }
        public long UserId { get; set; }
        public byte TicketStateId { get; set; }
        public string Message { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual TicketState TicketState { get; set; }
        public virtual User User { get; set; }
    }
}
