//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestrictedArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestrictedArea()
        {
            this.PointsByRestrictedAreas = new HashSet<PointsByRestrictedArea>();
            this.RestrictedAreas1 = new HashSet<RestrictedArea>();
        }
    
        public long Id { get; set; }
        public Nullable<long> RestrictedAreaId { get; set; }
        public Nullable<int> CenterId { get; set; }
        public Nullable<long> PersonId { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public byte RestrictionTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public string RepeatRules { get; set; }
        public bool OnAlert { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointsByRestrictedArea> PointsByRestrictedAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestrictedArea> RestrictedAreas1 { get; set; }
        public virtual RestrictedArea RestrictedArea1 { get; set; }
    }
}
