//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SimCard()
        {
            this.Devices = new HashSet<Device>();
            this.SimCardUses = new HashSet<SimCardUs>();
        }
    
        public long Id { get; set; }
        public int CenterId { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public int CarrierByCountryId { get; set; }
        public int SimCardTypeId { get; set; }
        public string Phone { get; set; }
        public string Serial { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual CarrierByCountry CarrierByCountry { get; set; }
        public virtual Center Center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimCardUs> SimCardUses { get; set; }
    }
}
