//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fenn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.AlertsByTickets = new HashSet<AlertsByTicket>();
            this.ResponsesByTickets = new HashSet<ResponsesByTicket>();
        }
    
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public int CenterId { get; set; }
        public long PersonId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public byte TicketStateId { get; set; }
        public string Message { get; set; }
        public bool WithAlerts { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertsByTicket> AlertsByTickets { get; set; }
        public virtual Center Center { get; set; }
        public virtual Location Location { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsesByTicket> ResponsesByTickets { get; set; }
        public virtual TicketState TicketState { get; set; }
        public virtual User User { get; set; }
    }
}
